// ISO 639-1 language codes supported by Whisper
export const LANGUAGES = [
  { code: 'auto', name: 'Automatisch erkennen (Originalsprache)' },
  { code: 'auto-translate', name: 'Automatisch erkennen (Ins Englische übersetzen)' },
  { code: 'en', name: 'Englisch' },
  { code: 'zh', name: 'Chinesisch' },
  { code: 'de', name: 'Deutsch' },
  { code: 'es', name: 'Spanisch' },
  { code: 'ru', name: 'Russisch' },
  { code: 'ko', name: 'Koreanisch' },
  { code: 'fr', name: 'Französisch' },
  { code: 'ja', name: 'Japanisch' },
  { code: 'pt', name: 'Portugiesisch' },
  { code: 'tr', name: 'Türkisch' },
  { code: 'pl', name: 'Polnisch' },
  { code: 'ca', name: 'Katalanisch' },
  { code: 'nl', name: 'Niederländisch' },
  { code: 'ar', name: 'Arabisch' },
  { code: 'sv', name: 'Schwedisch' },
  { code: 'it', name: 'Italienisch' },
  { code: 'id', name: 'Indonesisch' },
  { code: 'hi', name: 'Hindi' },
  { code: 'fi', name: 'Finnisch' },
  { code: 'vi', name: 'Vietnamesisch' },
  { code: 'he', name: 'Hebräisch' },
  { code: 'uk', name: 'Ukrainisch' },
  { code: 'el', name: 'Griechisch' },
  { code: 'ms', name: 'Malaiisch' },
  { code: 'cs', name: 'Tschechisch' },
  { code: 'ro', name: 'Rumänisch' },
  { code: 'da', name: 'Dänisch' },
  { code: 'hu', name: 'Ungarisch' },
  { code: 'ta', name: 'Tamilisch' },
  { code: 'no', name: 'Norwegisch' },
  { code: 'th', name: 'Thailändisch' },
  { code: 'ur', name: 'Urdu' },
  { code: 'hr', name: 'Kroatisch' },
  { code: 'bg', name: 'Bulgarisch' },
  { code: 'lt', name: 'Litauisch' },
];
